In [30]:
class Test:
    @staticmethod
    def assert_equals(a, b):
        assert a==b
        print('Passed')

In [65]:
#1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [43]:
#2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

import numpy as np
x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [44]:
#3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

import numpy as np
x = np.zeros((5,5))
for i in range (5):
    x[i,i-1] = i
print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [68]:
#4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.

import numpy as np
x=np.random.random((5,5))
for y in x:
    xE = np.mean(y)
    xstd=np.std(y)
    y = (y - xE)/xstd
    print(y)

[-0.15130874  0.55667546  0.85129148 -1.88390188  0.62724368]
[ 0.94819723 -0.42040154 -1.56438268 -0.16713889  1.20372588]
[ 1.32203034  0.75212763  0.06108859 -1.51660495 -0.61864161]
[-1.38335468  1.14841019  0.4798745   0.74563895 -0.99056896]
[-1.28971672  1.06493406  0.00515953 -0.93383647  1.1534596 ]


In [41]:
#5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

import numpy as np
y=np.random.uniform(0, 1, size=(10,3))
print(y)
for i in y:
    print(min(i,key=lambda x: abs(x-0.5)))

[[0.13882841 0.44189331 0.56602975]
 [0.7514533  0.50983897 0.85437231]
 [0.18551948 0.29445335 0.89591434]
 [0.8673735  0.86292398 0.04227961]
 [0.68946827 0.37508084 0.74815227]
 [0.93201315 0.12688875 0.61306972]
 [0.27568948 0.47282849 0.04223366]
 [0.10959128 0.78058751 0.34917583]
 [0.02727712 0.11848767 0.06778197]
 [0.79774243 0.73710509 0.25056279]]
0.4418933143106145
0.5098389653749141
0.2944533494422772
0.8629239770800649
0.3750808400551927
0.6130697154965783
0.4728284860395823
0.3491758266413977
0.11848766916736264
0.7371050943910182


In [45]:
#6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

import numpy as np
x = np.random.rand(6, 6)
print(x) 
print(np.sum(x,1)/np.max(x, 0))

[[0.20756677 0.79247615 0.93010797 0.60326521 0.33879006 0.62971723]
 [0.79791659 0.43885547 0.05242758 0.03515079 0.75560189 0.99108995]
 [0.97073022 0.87018398 0.48193834 0.61625196 0.00811222 0.6063763 ]
 [0.95156267 0.75065163 0.58254455 0.56357739 0.21540082 0.79493785]
 [0.38458969 0.54838495 0.65786197 0.90343094 0.98460299 0.9147511 ]
 [0.15470486 0.70005598 0.59934807 0.69641788 0.56577057 0.31400723]]
[3.60751453 3.52918731 3.8206242  4.27113432 4.46232817 3.0575475 ]


In [48]:
#7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(max((x[i] for i in range(1, len(x)) if x[i - 1] == 0), default=None))


5


In [56]:
#8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

import numpy as np
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in range (len(x)):
    x[j] = x[j] + np.count_nonzero(i == j)
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [64]:
#Задача со *. Создайте произвольный двумерный массив NxM, N, M > 1. На его основе создайте новый двумерный массив, значения в котором являются средним значением исходного во всевозможных окошках размера 2х2 со сдвигом 1 по вертикали и горизонтали.

import numpy as np
L = np.random.rand(10, 2)
A = np.array([(b[0, 0] + b[0, 1] + b[1, 0] + b[1, 1])/4 for a in np.lib.stride_tricks.sliding_window_view(L, (2, 2)) for b in a]).reshape(len(L[0:, 0])-1, len(L[0, 0:])-1)
print(A)

[[0.47776813]
 [0.32598534]
 [0.31481198]
 [0.60699171]
 [0.82477707]
 [0.69231075]
 [0.48524983]
 [0.3387694 ]
 [0.23046429]]
