In [30]:
class Test:
    @staticmethod
    def assert_equals(a, b):
        assert a==b
        print('Passed')

In [1]:
#1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [2]:
#2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.


x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [2]:
#3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули
import numpy as np
x = np.diag(np.arange(1, 5),-1)
print (x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [11]:
#4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.


x = np.random.random((5, 5))
m = np.mean(x, axis=1).reshape(-1,1)
x -= m
print(x)

[[-0.31824054  0.13783561 -0.08923732  0.10329156  0.16635069]
 [ 0.04840068  0.16064425 -0.19208622 -0.22161202  0.20465331]
 [-0.24614542 -0.18652028  0.13820525  0.10695105  0.1875094 ]
 [-0.22121152  0.32569744  0.13370128 -0.42356891  0.18538171]
 [-0.05239356 -0.23399135  0.45894517 -0.30863961  0.13607935]]


In [4]:
#5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

y = np.random.random((10, 3))
print(y)
print( y[range(10), np.abs(y - 0.5).argmin(axis=1)])

[[0.52943333 0.24668081 0.63445464]
 [0.1451653  0.96655545 0.28228971]
 [0.93795628 0.71045829 0.05076302]
 [0.8664487  0.48887796 0.94912262]
 [0.02851391 0.03806581 0.48029386]
 [0.45355565 0.17603098 0.21909182]
 [0.83341822 0.52126628 0.4251173 ]
 [0.46295663 0.27241545 0.44176462]
 [0.63589739 0.74639505 0.35246238]
 [0.32736806 0.83809542 0.18064383]]
[0.52943333 0.28228971 0.71045829 0.48887796 0.48029386 0.45355565
 0.52126628 0.46295663 0.63589739 0.32736806]


In [6]:
#6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

x = np.random.rand(6, 6)
print(x) 
print(np.sum(x,1)/np.max(x, 0))

[[0.19895027 0.64335104 0.86222333 0.52342053 0.91219546 0.40562667]
 [0.45142186 0.08221842 0.74323508 0.18752801 0.01883685 0.35323046]
 [0.5176714  0.69545057 0.76427622 0.75568242 0.00547694 0.55743355]
 [0.44221205 0.17069755 0.25222322 0.49010811 0.57657901 0.44933955]
 [0.08317082 0.78653221 0.27643291 0.6724528  0.36759218 0.88397367]
 [0.90600177 0.16435814 0.34787197 0.84409707 0.9445215  0.59269142]]
[3.91364279 2.33489571 3.82266521 2.82095459 3.25048671 4.29825232]


In [9]:
#7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.


x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
np.max(x[1:] [(x == 0)[:-1]])


5

In [7]:
#8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.


x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x + np.hstack((np.bincount(i), np.zeros(10-len(np.bincount(i)))))

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

In [9]:
#Задача со *. Создайте произвольный двумерный массив NxM, N, M > 1. На его основе создайте новый двумерный массив, значения в котором являются средним значением исходного во всевозможных окошках размера 2х2 со сдвигом 1 по вертикали и горизонтали.


L = np.random.rand(10, 2)
A = np.array([(b[0, 0] + b[0, 1] + b[1, 0] + b[1, 1])/4 for a in np.lib.stride_tricks.sliding_window_view(L, (2, 2)) for b in a]).reshape(len(L[0:, 0])-1, len(L[0, 0:])-1)
print(A)

[[0.48311393]
 [0.8812216 ]
 [0.72648941]
 [0.47624571]
 [0.61915088]
 [0.59136942]
 [0.44829521]
 [0.66150997]
 [0.54098901]]
